<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('colors')->insert([
            [ "css"=> 'aliceblue', "name"=> 'Alice Blue', "hex"=> '#f0f8ff' ],
            [ "css"=> 'antiquewhite', "name"=> 'Antique White', "hex"=> '#faebd7' ],
            [ "css"=> 'aqua', "name"=> 'Aqua', "hex"=> '#00ffff' ],
            [ "css"=> 'aquamarine', "name"=> 'Aquamarine', "hex"=> '#7fffd4' ],
            [ "css"=> 'azure', "name"=> 'Azure', "hex"=> '#f0ffff' ],
            [ "css"=> 'beige', "name"=> 'Beige', "hex"=> '#f5f5dc' ],
            [ "css"=> 'bisque', "name"=> 'Bisque', "hex"=> '#ffe4c4' ],
            [ "css"=> 'black', "name"=> 'Black', "hex"=> '#000000' ],
            [ "css"=> 'blanchedalmond', "name"=> 'Blanched Almond', "hex"=> '#ffebcd' ],
            [ "css"=> 'blue', "name"=> 'Blue', "hex"=> '#0000ff' ],
            [ "css"=> 'blueviolet', "name"=> 'Blue Violet', "hex"=> '#8a2be2' ],
            [ "css"=> 'brown', "name"=> 'Brown', "hex"=> '#a52a2a' ],
            [ "css"=> 'burlywood', "name"=> 'Burlywood', "hex"=> '#deb887' ],
            [ "css"=> 'cadetblue', "name"=> 'Cadet Blue', "hex"=> '#5f9ea0' ],
            [ "css"=> 'chartreuse', "name"=> 'Chartreuse', "hex"=> '#7fff00' ],
            [ "css"=> 'chocolate', "name"=> 'Chocolate', "hex"=> '#d2691e' ],
            [ "css"=> 'coral', "name"=> 'Coral', "hex"=> '#ff7f50' ],
            [ "css"=> 'cornflowerblue', "name"=> 'Cornflower Blue', "hex"=> '#6495ed' ],
            [ "css"=> 'cornsilk', "name"=> 'Cornsilk', "hex"=> '#fff8dc' ],
            [ "css"=> 'crimson', "name"=> 'Crimson', "hex"=> '#dc143c' ],
            [ "css"=> 'cyan', "name"=> 'Cyan', "hex"=> '#00ffff' ],
            [ "css"=> 'darkblue', "name"=> 'Dark Blue', "hex"=> '#00008b' ],
            [ "css"=> 'darkcyan', "name"=> 'Dark Cyan', "hex"=> '#008b8b' ],
            [ "css"=> 'darkgoldenrod', "name"=> 'Dark Goldenrod', "hex"=> '#b8860b' ],
            [ "css"=> 'darkgray', "name"=> 'Dark Gray', "hex"=> '#a9a9a9' ],
            [ "css"=> 'darkgreen', "name"=> 'Dark Green', "hex"=> '#006400' ],
            [ "css"=> 'darkgrey', "name"=> 'Dark Grey', "hex"=> '#a9a9a9' ],
            [ "css"=> 'darkkhaki', "name"=> 'Dark Khaki', "hex"=> '#bdb76b' ],
            [ "css"=> 'darkmagenta', "name"=> 'Dark Magenta', "hex"=> '#8b008b' ],
            [ "css"=> 'darkolivegreen', "name"=> 'Dark Olive Green', "hex"=> '#556b2f' ],
            [ "css"=> 'darkorange', "name"=> 'Dark Orange', "hex"=> '#ff8c00' ],
            [ "css"=> 'darkorchid', "name"=> 'Dark Orchid', "hex"=> '#9932cc' ],
            [ "css"=> 'darkred', "name"=> 'Dark Red', "hex"=> '#8b0000' ],
            [ "css"=> 'darksalmon', "name"=> 'Dark Salmon', "hex"=> '#e9967a' ],
            [ "css"=> 'darkseagreen', "name"=> 'Dark Sea Green', "hex"=> '#8fbc8f' ],
            [ "css"=> 'darkslateblue', "name"=> 'Dark Slate Blue', "hex"=> '#483d8b' ],
            [ "css"=> 'darkslategrey', "name"=> 'Dark Slate Grey', "hex"=> '#2f4f4f' ],
            [ "css"=> 'darkturquoise', "name"=> 'Dark Turquoise', "hex"=> '#00ced1' ],
            [ "css"=> 'darkviolet', "name"=> 'Dark Violet', "hex"=> '#9400d3' ],
            [ "css"=> 'deeppink', "name"=> 'Deep Pink', "hex"=> '#ff1493' ],
            [ "css"=> 'deepskyblue', "name"=> 'Deep Sky Blue', "hex"=> '#00bfff' ],
            [ "css"=> 'dimgray', "name"=> 'Dim Gray', "hex"=> '#696969' ],
            [ "css"=> 'dimgrey', "name"=> 'Dim Grey', "hex"=> '#696969' ],
            [ "css"=> 'dodgerblue', "name"=> 'Dodger Blue', "hex"=> '#1e90ff' ],
            [ "css"=> 'firebrick', "name"=> 'Firebrick', "hex"=> '#b22222' ],
            [ "css"=> 'floralwhite', "name"=> 'Floral White', "hex"=> '#fffaf0' ],
            [ "css"=> 'forestgreen', "name"=> 'Forest Green', "hex"=> '#228b22' ],
            [ "css"=> 'fuchsia', "name"=> 'Fuchsia', "hex"=> '#ff00ff' ],
            [ "css"=> 'gainsboro', "name"=> 'Gainsboro', "hex"=> '#dcdcdc' ],
            [ "css"=> 'ghostwhite', "name"=> 'Ghost White', "hex"=> '#f8f8ff' ],
            [ "css"=> 'goldenrod', "name"=> 'Goldenrod', "hex"=> '#daa520' ],
            [ "css"=> 'gold', "name"=> 'Gold', "hex"=> '#ffd700' ],
            [ "css"=> 'gray', "name"=> 'Gray', "hex"=> '#808080' ],
            [ "css"=> 'green', "name"=> 'Green', "hex"=> '#008000' ],
            [ "css"=> 'greenyellow', "name"=> 'Green Yellow', "hex"=> '#adff2f' ],
            [ "css"=> 'grey', "name"=> 'Grey', "hex"=> '#808080' ],
            [ "css"=> 'honeydew', "name"=> 'Honeydew', "hex"=> '#f0fff0' ],
            [ "css"=> 'hotpink', "name"=> 'Hot Pink', "hex"=> '#ff69b4' ],
            [ "css"=> 'indianred', "name"=> 'Indian Red', "hex"=> '#cd5c5c' ],
            [ "css"=> 'indigo', "name"=> 'Indigo', "hex"=> '#4b0082' ],
            [ "css"=> 'ivory', "name"=> 'Ivory', "hex"=> '#fffff0' ],
            [ "css"=> 'khaki', "name"=> 'Khaki', "hex"=> '#f0e68c' ],
            [ "css"=> 'lavenderblush', "name"=> 'Lavender Blush', "hex"=> '#fff0f5' ],
            [ "css"=> 'lavender', "name"=> 'Lavender', "hex"=> '#e6e6fa' ],
            [ "css"=> 'lawngreen', "name"=> 'Lawn Green', "hex"=> '#7cfc00' ],
            [ "css"=> 'lemonchiffon', "name"=> 'Lemon Chiffon', "hex"=> '#fffacd' ],
            [ "css"=> 'lightblue', "name"=> 'Light Blue', "hex"=> '#add8e6' ],
            [ "css"=> 'lightcoral', "name"=> 'Light Coral', "hex"=> '#f08080' ],
            [ "css"=> 'lightcyan', "name"=> 'Light Cyan', "hex"=> '#e0ffff' ],
            [ "css"=> 'lightgoldenrodyellow', "name"=> 'Light Goldenrod Yellow', "hex"=> '#fafad2' ],
            [ "css"=> 'lightgray', "name"=> 'Light Gray', "hex"=> '#d3d3d3' ],
            [ "css"=> 'lightgreen', "name"=> 'Light Green', "hex"=> '#90ee90' ],
            [ "css"=> 'lightgrey', "name"=> 'Light Grey', "hex"=> '#d3d3d3' ],
            [ "css"=> 'lightpink', "name"=> 'Light Pink', "hex"=> '#ffb6c1' ],
            [ "css"=> 'lightsalmon', "name"=> 'Light Salmon', "hex"=> '#ffa07a' ],
            [ "css"=> 'lightseagreen', "name"=> 'Light Sea Green', "hex"=> '#20b2aa' ],
            [ "css"=> 'lightskyblue', "name"=> 'Light Sky Blue', "hex"=> '#87cefa' ],
            [ "css"=> 'lightslategray', "name"=> 'Light Slate Gray', "hex"=> '#778899' ],
            [ "css"=> 'lightsteelblue', "name"=> 'Light Steel Blue', "hex"=> '#b0c4de' ],
            [ "css"=> 'lightyellow', "name"=> 'Light Yellow', "hex"=> '#ffffe0' ],
            [ "css"=> 'lime', "name"=> 'Lime', "hex"=> '#00ff00' ],
            [ "css"=> 'limegreen', "name"=> 'Lime Green', "hex"=> '#32cd32' ],
            [ "css"=> 'linen', "name"=> 'Linen', "hex"=> '#faf0e6' ],
            [ "css"=> 'magenta', "name"=> 'Magenta', "hex"=> '#ff00ff' ],
            [ "css"=> 'maroon', "name"=> 'Maroon', "hex"=> '#800000' ],
            [ "css"=> 'mediumaquamarine', "name"=> 'Medium Aquamarine', "hex"=> '#66cdaa' ],
            [ "css"=> 'mediumblue', "name"=> 'Medium Blue', "hex"=> '#0000cd' ],
            [ "css"=> 'mediumorchid', "name"=> 'Medium Orchid', "hex"=> '#ba55d3' ],
            [ "css"=> 'mediumpurple', "name"=> 'Medium Purple', "hex"=> '#9370db' ],
            [ "css"=> 'mediumseagreen', "name"=> 'Medium Sea Green', "hex"=> '#3cb371' ],
            [ "css"=> 'mediumslateblue', "name"=> 'Medium Slate Blue', "hex"=> '#7b68ee' ],
            [ "css"=> 'mediumspringgreen', "name"=> 'Medium Spring Green', "hex"=> '#00fa9a' ],
            [ "css"=> 'mediumturquoise', "name"=> 'Medium Turquoise', "hex"=> '#48d1cc' ],
            [ "css"=> 'mediumvioletred', "name"=> 'Medium Violet Red', "hex"=> '#c71585' ],
            [ "css"=> 'midnightblue', "name"=> 'Midnight Blue', "hex"=> '#191970' ],
            [ "css"=> 'mintcream', "name"=> 'Mint Cream', "hex"=> '#f5fffa' ],
            [ "css"=> 'mistyrose', "name"=> 'Misty Rose', "hex"=> '#ffe4e1' ],
            [ "css"=> 'moccasin', "name"=> 'Moccasin', "hex"=> '#ffe4b5' ],
            [ "css"=> 'navajowhite', "name"=> 'Navajo White', "hex"=> '#ffdead' ],
            [ "css"=> 'navy', "name"=> 'Navy', "hex"=> '#000080' ],
            [ "css"=> 'oldlace', "name"=> 'Old Lace', "hex"=> '#fdf5e6' ],
            [ "css"=> 'olive', "name"=> 'Olive', "hex"=> '#808000' ],
            [ "css"=> 'olivedrab', "name"=> 'Olive Drab', "hex"=> '#6b8e23' ],
            [ "css"=> 'orange', "name"=> 'Orange', "hex"=> '#ffa500' ],
            [ "css"=> 'orangered', "name"=> 'Orange Red', "hex"=> '#ff4500' ],
            [ "css"=> 'orchid', "name"=> 'Orchid', "hex"=> '#da70d6' ],
            [ "css"=> 'palegoldenrod', "name"=> 'Pale Goldenrod', "hex"=> '#eee8aa' ],
            [ "css"=> 'palegreen', "name"=> 'Pale Green', "hex"=> '#98fb98' ],
            [ "css"=> 'paleturquoise', "name"=> 'Pale Turquoise', "hex"=> '#afeeee' ],
            [ "css"=> 'palevioletred', "name"=> 'Pale Violet Red', "hex"=> '#db7093' ],
            [ "css"=> 'papayawhip', "name"=> 'Papaya Whip', "hex"=> '#ffefd5' ],
            [ "css"=> 'peachpuff', "name"=> 'Peach Puff', "hex"=> '#ffdab9' ],
            [ "css"=> 'peru', "name"=> 'Peru', "hex"=> '#cd853f' ],
            [ "css"=> 'pink', "name"=> 'Pink', "hex"=> '#ffc0cb' ],
            [ "css"=> 'plum', "name"=> 'Plum', "hex"=> '#dda0dd' ],
            [ "css"=> 'powderblue', "name"=> 'Powder Blue', "hex"=> '#b0e0e6' ],
            [ "css"=> 'purple', "name"=> 'Purple', "hex"=> '#800080' ],
            [ "css"=> 'rebeccapurple', "name"=> 'Rebecca Purple', "hex"=> '#663399' ],
            [ "css"=> 'red', "name"=> 'Red', "hex"=> '#ff0000' ],
            [ "css"=> 'rosybrown', "name"=> 'Rosy Brown', "hex"=> '#bc8f8f' ],
            [ "css"=> 'royalblue', "name"=> 'Royal Blue', "hex"=> '#4169e1' ],
            [ "css"=> 'saddlebrown', "name"=> 'Saddle Brown', "hex"=> '#8b4513' ],
            [ "css"=> 'salmon', "name"=> 'Salmon', "hex"=> '#fa8072' ],
            [ "css"=> 'sandybrown', "name"=> 'Sandy Brown', "hex"=> '#f4a460' ],
            [ "css"=> 'seagreen', "name"=> 'Sea Green', "hex"=> '#2e8b57' ],
            [ "css"=> 'seashell', "name"=> 'Seashell', "hex"=> '#fff5ee' ],
            [ "css"=> 'sienna', "name"=> 'Sienna', "hex"=> '#a0522d' ],
            [ "css"=> 'silver', "name"=> 'Silver', "hex"=> '#c0c0c0' ],
            [ "css"=> 'skyblue', "name"=> 'Sky Blue', "hex"=> '#87ceeb' ],
            [ "css"=> 'slateblue', "name"=> 'Slate Blue', "hex"=> '#6a5acd' ],
            [ "css"=> 'slategray', "name"=> 'Slate Gray', "hex"=> '#708090' ],
            [ "css"=> 'slategrey', "name"=> 'Slate Grey', "hex"=> '#708090' ],
            [ "css"=> 'snow', "name"=> 'Snow', "hex"=> '#fffafa' ],
            [ "css"=> 'springgreen', "name"=> 'Spring Green', "hex"=> '#00ff7f' ],
            [ "css"=> 'steelblue', "name"=> 'Steel Blue', "hex"=> '#4682b4' ],
            [ "css"=> 'tan', "name"=> 'Tan', "hex"=> '#d2b48c' ],
            [ "css"=> 'teal', "name"=> 'Teal', "hex"=> '#008080' ],
            [ "css"=> 'thistle', "name"=> 'Thistle', "hex"=> '#d8bfd8' ],
            [ "css"=> 'tomato', "name"=> 'Tomato', "hex"=> '#ff6347' ],
            [ "css"=> 'turquoise', "name"=> 'Turquoise', "hex"=> '#40e0d0' ],
            [ "css"=> 'violet', "name"=> 'Violet', "hex"=> '#ee82ee' ],
            [ "css"=> 'wheat', "name"=> 'Wheat', "hex"=> '#f5deb3' ],
            [ "css"=> 'white', "name"=> 'White', "hex"=> '#ffffff' ],
            [ "css"=> 'whitesmoke', "name"=> 'White Smoke', "hex"=> '#f5f5f5' ],
            [ "css"=> 'yellow', "name"=> 'Yellow', "hex"=> '#ffff00' ],
            [ "css"=> 'yellowgreen', "name"=> 'Yellow Green', "hex"=> '#9acd32' ]
        ]);
    }
}
